Repository WhiteClover4/SecondHand-FE, pull requests merged in 2022-10, with the labels that each got.

#118 Fix/search input z index
  package.json
  yarn.lock
Labels: bug, hacktoberfest

#121 feat: add rot13 encryption
  src/constants/encryption.js
  src/hooks/dependent/useAuth.js
Labels: enhancement, hacktoberfest-accepted

#120 feat: add condition is your product at product detail
  src/hooks/dependent/useSellerProduct.js
  src/pages/product/[product_name].js
Labels: enhancement, hacktoberfest-accepted

#119 fix: remove all alerts in 3 seconds
  src/App.js
  src/components/alerts/MainAlert.js
  src/redux/slice/alert.js
Labels: bug, hacktoberfest-accepted

#132 styling primary button add hover
  src/pages/Home.js
  yarn.lock
Labels: enhancement, hacktoberfest-accepted

#135 Styling/email
  src/hooks/dependent/useAuth.js
Labels: bug, hacktoberfest-accepted
